import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import {serverSideTranslations} from "next-i18next/serverSideTranslations";

import {Navbar} from "@components/ui";
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Mofid Multi App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Navbar />
      </main>
    </div>
  );
}

export async function getStaticProps({locale}) {
  return {
    props: {
      ...(await serverSideTranslations(locale, ["common"])),
    },
  };
}
